apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  namespace: beta
spec:
  rules:
  - host: beta.solrr.net
    http:
      paths:
      - backend:
          serviceName: default-frontend
          servicePort: 80
