apiVersion: v1
kind: Service
metadata:
        name: default-frontend
        namespace: beta
spec:
        selector:
                app: solrr.net
        ports:
        - protocol: TCP
          port: 80
          targetPort: 80
